version: '3.5'

services:
  mongodb:
    container_name: db-mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_NAME}
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db
    networks:
      - mongodb
    restart: unless-stopped  

networks:
  mongodb:
    driver: bridge

volumes:
  mongo_data: